<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gress" />
    <PackageReference Include="JsonExtensions" />
    <PackageReference Include="PowerKit" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="YoutubeExplode" />
    <PackageReference Include="YoutubeExplode.Converter" />
  </ItemGroup>
</Project>
